language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04, Debug
      dist: trusty
      sudo: required
      dotnet: 2.0.0
      env:
        - CONFIGURATION=Debug
    - os: linux # Ubuntu 14.04, Release
      dist: trusty
      sudo: required
      dotnet: 2.0.0
      env:
        - CONFIGURATION=Release
    - os: osx # OSX 10.11, Debug
      osx_image: xcode7.2
      dotnet: 2.0.0
      env:
        - CONFIGURATION=Debug
    - os: osx # OSX 10.11, Release
      osx_image: xcode7.2
      dotnet: 2.0.0
      env:
        - CONFIGURATION=Release
    - os: osx # OSX 10.12, Debug
      osx_image: xcode7.3
      dotnet: 2.0.0
      env:
        - CONFIGURATION=Debug
    - os: osx # OSX 10.12, Release
      osx_image: xcode7.3
      dotnet: 2.0.0
      env:
        - CONFIGURATION=Release

script:
  - dotnet --info
  - dotnet restore --no-cache
  - dotnet build --configuration ${CONFIGURATION}
