# Copyright (c) E5R Development Team. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

language: c

addons:  
  apt:
    packages:
    - libunwind8
    - libunwind8-dev
    - gettext
    - libicu-dev
    - liblttng-ust-dev
    - libcurl4-openssl-dev
    - libssl-dev
    - uuid-dev
    - unzip

matrix:
  include:
    - os: linux # Ubuntu 14.04, Debug
      dist: trusty
      sudo: required
      env:
        - CONFIGURATION=Debug
        - CLI_VERSION=2.0.0
        - VERSION=1.0.0
    - os: linux # Ubuntu 14.04, Release
      dist: trusty
      sudo: required
      env:
        - CONFIGURATION=Release
        - CLI_VERSION=2.0.0
        - VERSION=1.0.0
    - os: osx # OSX 10.12, Debug
      osx_image: xcode7.3
      env:
        - CONFIGURATION=Debug
        - CLI_VERSION=2.0.0
        - VERSION=1.0.0
    - os: osx # OSX 10.12, Release
      osx_image: xcode7.3
      env:
        - CONFIGURATION=Release
        - CLI_VERSION=2.0.0
        - VERSION=1.0.0

install:
  - ./build/install.sh

script:
  - ./build/build.sh
  - ./build/test.sh
