# Copyright (c) E5R Development Team. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

version: 1.0.0-dev-b{build}
image: Visual Studio 2017

environment:
  CLI_VERSION: 2.0.0

configuration:
- Debug
- Release

platform:
- x86
- x64

install:
  - ps: & .\build\install.ps1
  - ps: $env:Path = "$pwd\.dotnetsdk;$env:Path"

build_script:
  - ps: dotnet --info
  - ps: dotnet restore --no-cache
  - ps: dotnet build --configuration $env:CONFIGURATION
  - ps: dotnet pack "$pwd\src\E5R.Sdk.Bit\E5R.Sdk.Bit.csproj" --configuration $env:CONFIGURATION /p:VersionPrefix="$env:APPVEYOR_BUILD_VERSION"

cache:
  - .\.dotnetsdk

test_script:
  - ps: dotnet test
  # E5R.Sdk.Bit.Test
  - ps: dotnet test .\test\E5R.Sdk.Bit.Test\E5R.Sdk.Bit.Test.csproj
  # E5R.Tools.Bit.Engine.Test
  - ps: dotnet test .\test\E5R.Tools.Bit.Engine.Test\E5R.Tools.Bit.Engine.Test.csproj
  # E5R.Tools.Bit.Test
  - ps: dotnet test .\test\E5R.Tools.Bit.Test\E5R.Tools.Bit.Test.csproj

artifacts:
  - path: 'src\**\*.nupkg'
