version: 1.0.0-dev-b{build}
image: Visual Studio 2017

environment:
  CLI_VERSION: 2.0.0

configuration:
- Debug
- Release

platform:
- x86
- x64

install:
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: 'if (-not ("$env:DOTNET_INSTALL_DIR/dotnet.exe" | Test-Path)){ Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" }'
  - ps: 'if (-not ("$env:DOTNET_INSTALL_DIR/dotnet.exe" | Test-Path)){ & "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Architecture $env:PLATFORM -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR }'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  - ps: dotnet --info
  - ps: dotnet restore --no-cache
  - ps: dotnet build --configuration $env:CONFIGURATION

cache:
  - .\.dotnetsdk

test:
  assemblies:
    only:
    - 'test\**\*.Test.dll'

  categories:
    only:
    - UNIT

artifacts:
  - path: 'src\**\*.nupkg'
