# Copyright (c) E5R Development Team. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

version: 1.0.0-dev-b{build}
image: Visual Studio 2017

configuration:
- Debug
- Release

platform:
- x64

build_script:
  - ps: '& .\build-coreclr.ps1 -Target Build'

cache:
  - .\build\.dotnetsdk

test_script:
  - ps: '& .\build-coreclr.ps1 -Target Test'

artifacts:
  - path: 'src\**\*.nupkg'
