version: 1.0.0-dev-b{build}
image: Visual Studio 2017

environment:
  CLI_VERSION: 2.0.0

configuration:
- Debug
- Release

platform:
- x86
- x64

install:
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: 'if (-not ("$env:DOTNET_INSTALL_DIR/dotnet.exe" | Test-Path)){ Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" }'
  - ps: 'if (-not ("$env:DOTNET_INSTALL_DIR/dotnet.exe" | Test-Path)){ & "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Architecture $env:PLATFORM -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR }'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  - ps: dotnet --info
  - ps: dotnet restore --no-cache
  - ps: dotnet build --configuration $env:CONFIGURATION
  - ps: dotnet pack "$pwd\src\E5R.Sdk.Bit\E5R.Sdk.Bit.csproj" --configuration $env:CONFIGURATION /p:VersionPrefix="$env:APPVEYOR_BUILD_VERSION"

cache:
  - .\.dotnetsdk

test_script:
  # E5R.Sdk.Bit.Test
  - ps: cd "$env:APPVEYOR_BUILD_FOLDER\test\E5R.Sdk.Bit.Test"
  - ps: dotnet xunit --no-build
  # E5R.Tools.Bit.Engine.Test
  - ps: cd "$env:APPVEYOR_BUILD_FOLDER\test\E5R.Tools.Bit.Engine.Test"
  - ps: dotnet xunit --no-build
  # E5R.Tools.Bit.Test
  - ps: cd "$env:APPVEYOR_BUILD_FOLDER\test\E5R.Tools.Bit.Test"
  - ps: dotnet xunit --no-build

artifacts:
  - path: 'src\**\*.nupkg'
