# Copyright (c) E5R Development Team. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

version: 1.0.0-dev-b{build}
image: Visual Studio 2017

environment:
  CLI_VERSION: 2.0.0

configuration:
- Debug
- Release

platform:
- x86
- x64

install:
  - ps: '& .\build\install.ps1'

build_script:
  - ps: '& .\build\build.ps1'

cache:
  - .\.dotnetsdk

test_script:
  - ps: '& .\build\test.ps1'

artifacts:
  - path: 'src\**\*.nupkg'
